### ISSUE TITLE
UI - Remove Spacing between filter options

### ISSUE THREAD

**Issue by e01010100** [CoalitionBuilder/okcongress#6]
Currently between each set of radio buttons there is a break; for example: All, House of Representatives, and Senate. Between each option of a particular radio button set there shouldn't be empty spaces.

I'm not exactly sure which css attributes would need to be adjusted to make this happen.

**Comment by bschmoker** [comment]
i can look at this real quick

**Comment by bschmoker** [comment]
Done in pr
